### PR TITLE
Add updated 4.1 notebook

### PR DESCRIPTION
**Pull request by cbur24**
This PR is for working on the week 4 practicals. As agreed, two of the notebooks have been removed, leaving just the one updated notebook for review.

### CODE REVIEW

**Comment by myebra** [comment]
Hi all, I have corrected some typos and change a bit the definitions and language used to match it better with the content of the lectures. Otherwise it looks better!

Then I have some questions

1. “Training data” - I think on Friday we agreed that students would collect a few samples as training data so they learn how to do it but we will provide a final training dataset for them. If I am correct, we should them ask the students to collect training data for one class for example? water? urban area? and clarify that in the tutorial. It would be good to give the students a guide on what categories to select
2. “#### After collecting training samples, you can convert the samples to shapefile and then load training data from the system's path.” Is the training_data.shp the training data we provide to them to run the classification or is that the file that they have created? As indicated before it should be the earlier but it is not clear in the tutorial
3. Line 84 “* Set its parameters if necessary” why “if necessary”?-
4. line 94- ### Post-classification methods- In the theory we talk about post-classification methods to filters you apply such as majority model ...  to reduce the spatial fragmentation of the classified images that is why I have changed the title
5. I have removed line 94 as they have not learn much about vegetation indices yet (they will learn all the indices next week)
6. Line 104 “Create a 2 band image with the area image and the classified image” what is the area image??
7. I am not very sure how useful the exercise 2 of choosing different percentages in the training and validations samples  is- perhaps we can remove it given we ask the students at the end to re-run the classification to improve the results which whatever criteria they think is best. Instead we can ask them a few questions around comparing the results of the exercise 1 where they used the same sample for calibration and validation and the use of 70/30.

**Comment by cbur24** [comment]
I've made the edits listed below.  Once I have access to the training samples, I will update the code to use those and then test that all the code works. 

- Add more text around good practices for collecting training data, along with links to other open-source platforms for collecting training data, and a couple of review articles on ML and TD
- Added an unmarked exercise for collecting training samples
- Add a cloud masking and rescaling function for loading Sentinel-2!
- Removed the question from exercise 1: `"Was the classification satisfactory"` as I'm not sure how the students would answer that. I added the question: `"What was the overall omission error? what was the overall commission error?"` This will test their understanding of confusion matrices. 
- Re-wrote Exercise 2
- Added clarifications in the markdown throughout

**Comment by cbur24** [comment]
@myebra I have now tested the notebook from start to finish and it all seems to be working. I made some more edits:
- converting `ee.confusionMatrix` objects in a tidy Pandas Dataframe that the students can more effectively read
- Fixed a few bugs in the code
- Simpler plotting of the class areas.

**Comment by myebra** [comment]
I think the lab looks good! 

I have fixed a few more typos.

Quesitons.
1. I like to introduce the students to other potential tools to collect training data but when I clicked on the links provided it was not straightforward to me how to use those tools... I am not sure if there will be time to explain those in the class or if there is any short video available online or another resource to add -- If not resources and there is no time perhaps it is better to remove.

2. In the accuracy assessment section "Use test samples to assess the accuracy of a classifier using a confusion matrix..." I am not sure if it is clear what "test samples" means here, can we be more clear?
3. 
Thanks all for your work on this tutorial.

**Pull request merged**
